### PR TITLE
pulling updates 

### PR DESCRIPTION
**Pull request by siruslan**

### CODE REVIEW

**Comment by fnordfish** [comment]
This change just broke our Nginx configuration. `/var/www` was owned by root and `/var/www/webroot` by nginx. Now, the still somewhat running app (using the nginx user) cannot write files anymore.

**Comment by siruslan** [comment]
@fnordfish do you use my fork? the master repo is located here https://github.com/jelastic-jps/lets-encrypt/

**Comment by fnordfish** [comment]
Sorry, just realized this was a fork. Not 100% sure how I ended up here. Anyhow, this got merged, wasn’t it?
The `chown -R apache:apache /var/www` matches exactly what we’re facing after just updating our certs :(

**Comment by fnordfish** [comment]
Never mind, I’ll open a ticket upstream. Sorry for the spam

**Comment by siruslan** [comment]
@fnordfish I'm testing improvement, and push updates to the upstream time-to-time. But it's better to have a discussion at the upstream. I can't find your issue here https://github.com/jelastic-jps/lets-encrypt/issues. Is it related to jelastic add-on?

**Comment by fnordfish** [comment]
Just opened an issue at jelastic-jps/lets-encrypt#25

**Pull request merged**
